export enum BadgeCategory {
  PERSONALITY = 'PERSONALITY',
  TEAMWORK = 'TEAMWORK',
  ROLEPLAY = 'ROLEPLAY',
  GAMEPLAY = 'GAMEPLAY',
  COMMUNICATION = 'COMMUNICATION',
  COMMITMENT = 'COMMITMENT',
  CREATIVITY = 'CREATIVITY',
  LEADERSHIP = 'LEADERSHIP',
  SAFETY = 'SAFETY',
  OTHER = 'OTHER',
}
