export enum NotificationType {
  REQUEST_RECEIVED = 'REQUEST_RECEIVED',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  PLAYER_KICKED = 'PLAYER_KICKED',
  NEW_MESSAGE = 'NEW_MESSAGE',
}
